on:
  workflow_dispatch:
  push:
    branches:
      - extui-align
  pull_request:
    branches:
      - extui-align

jobs:
  build:
    name: deploy standalone build for arch-linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Cache ccache directory
      - name: Cache ccache directory
        id: cache-ccache
        uses: actions/cache@v4
        with:
          path: .ccache
          key: ${{ runner.os }}-ccache-${{ hashFiles('CMakeLists.txt', '**/CMakeLists.txt', '**/*.cpp', '**/*.h') }}
          restore-keys: |
            ${{ runner.os }}-ccache-
    
      - name: Docker for Arch
        run: |
          docker pull archlinux:base-devel
          docker run --rm \
            -v $GITHUB_WORKSPACE:/workspace \
            -v $GITHUB_WORKSPACE/.ccache:/workspace/.ccache \
            -w /workspace \
            -e CCACHE_DIR=/workspace/.ccache \
            archlinux:base-devel bash -c "
             
              pacman -Syu --noconfirm &&
              pacman -S --noconfirm \
                cmake \
                ninja \
                qt5-base \
                qt5-multimedia \
                openal \
                sdl2 \
                glu \
                ccache &&
              
              mkdir -p build out &&
              
              export PATH=/usr/lib/ccache:$PATH && 

              cmake -G Ninja -S ./yabause -B ./build \
                -DCMAKE_INSTALL_PREFIX='./out' \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_COMPILER="ccache gcc" \
                -DCMAKE_CXX_COMPILER="ccache g++" \
                -DYAB_USE_QT5=ON

              ninja -C ./build && ninja -C ./build install
            "

      # Step 6: Upload build artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: kronos-artifact
          path: ./out/
