on:
  workflow_dispatch:
  push:
    branches:
    - extui-align
  pull_request:
    branches:
    - extui-align

jobs:
  build:
    name: deploy standalone build for arch-linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Step 1: Ensure the ./build folder exists
      - name: Ensure build directory exists
        run: |
          mkdir -p ./build  # Create the build directory if it doesn't already exist
          ls 
        
      - name: Cache CMake build and intermediate files
        uses: actions/cache@v4
        with:
          path: |
            ./build  # Cache the entire build directory
          key: ${{ runner.os }}-kronos-build-${{ hashFiles('**/*.cpp', '**/*.h', '**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-kronos-build-  
            
      - name: Docker for Arch
        run: |
          docker pull archlinux:base-devel
          docker run --rm \
            -v $PWD:/workspace \
            -v $PWD/build:/workspace/build \
            -w /workspace \
            archlinux:base-devel bash -c "
              pacman -Syu --noconfirm &&
              pacman -S --noconfirm \
                cmake \
                ninja \
                qt5-base \
                qt5-multimedia \
                openal \
                sdl2 \
                glu &&
              mkdir -p build out &&
              cmake -G Ninja -S ./yabause -B ./build \
                -DCMAKE_INSTALL_PREFIX="./out" \
                -DCMAKE_BUILD_TYPE=Release \
                -DYAB_USE_QT5=ON \
              &&
              ninja -C ./build && ninja -C ./build install
            "
            
#      - name: Compress the output directory
#        run: |
#          # Compress the 'out' directory into a .tar.gz archive
#          tar -czvf out.tar.gz -C ./out .

#      - name: Upload build artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: build-artifacts
#          path: out.tar.gz  # Upload the compressed tarball
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: kronos-artifact 
          path: ./out/ 
