on:
  workflow_dispatch:
  push:
    branches:
      - extui-align
  pull_request:
    branches:
      - extui-align

jobs:
  build:
    name: deploy standalone build for arch-linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Step 1: Ensure build directory exists
      - name: Ensure build directory exists
        run: |
          mkdir -p ./build  # Create the build directory if it doesn't already exist

      # Step 2: Docker for Arch - Build Process (this step will populate ./build)
      - name: Docker for Arch
        run: |
          docker pull archlinux:base-devel
          docker run --rm \
            -v $PWD:/workspace \
            -v $PWD/build:/workspace/build \
            -w /workspace \
            archlinux:base-devel bash -c "
              pacman -Syu --noconfirm &&
              pacman -S --noconfirm \
                cmake \
                ninja \
                qt5-base \
                qt5-multimedia \
                openal \
                sdl2 \
                glu &&
              mkdir -p build out &&
              cmake -G Ninja -S ./yabause -B ./build \
                -DCMAKE_INSTALL_PREFIX='./out' \
                -DCMAKE_BUILD_TYPE=Release \
                -DYAB_USE_QT5=ON \
              &&
              ninja -C ./build && ninja -C ./build install
            "

      # Step 3: Cache CMake build and intermediate files (now this step happens after the build)
      - name: Cache CMake build and intermediate files
        uses: actions/cache@v4
        with:
          path: |
            ./build  # Cache the entire build directory (after the build has populated it)
          key: ${{ runner.os }}-kronos-build-${{ hashFiles('**/*.cpp', '**/*.h', '**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-kronos-build-

      # Step 4: Upload build artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: kronos-artifact 
          path: ./out/
